### ISSUE TITLE
사진이 안 올라감

### ISSUE THREAD

**Issue by jini031104** [foodsns/Frontend#112]
깃허브에 올라온 주소에는 문제 없음. 로컬호스트주소에서만 해당 오류 발생.

![image](https://user-images.githubusercontent.com/90189794/140172368-6499e75f-8207-4df6-9d62-1f282b63426a.png)

다음과 같은 오류가 뜨면서 올라가지 않음

![일러스트3](https://user-images.githubusercontent.com/90189794/140173338-baf5e4d3-1a4b-40f9-824a-6950fe5ef48a.png)

**Comment by knh4437** [comment]
혹시 npm i 한번 해봐주실 수 있나요? vue 버전 3에서 저런 오류가 생기더라고요. 현우님이 3에서 2로 버전을 낮춰주셨어서 재설치 한번 해봐주세요

**Comment by jini031104** [comment]
이제 되네요. 감사합니다!
