### ISSUE TITLE
좋아요목록 로그인 동작을 해야만 접속 가능

### ISSUE THREAD

**Issue by jini031104** [foodsns/Frontend#114]
### 문제

로그인이 되어 있는 상태로 사이트에 들어가면 좋아요 버튼이 활성화가 안 됨. 아래 사진 오른쪽을 보면 로그인이 되었음에도 '로그인x' 라고 뜨는 것을 볼 수 있음.

![image](https://user-images.githubusercontent.com/90189794/140287149-8b9dff7b-f91e-4d31-a2e0-f63dc40742a5.png)

### 이유

```Vue.prototype.$firebaseAuth.getCurrentUserUid()``` 코드가 로그인 과정을 거쳐야만 null이 아니게 되는 것 같음. 실제로 로그아웃을 한 후 다시 로그인을 하면 좋아요 목록이 활성화되는 것을 볼 수 있음.

![image](https://user-images.githubusercontent.com/90189794/140287755-832c7748-fe39-4f96-bb76-09f6cf3548b1.png)

### 결론

로그인 상태를 가져오는 걸 찾아야함.

**Comment by stories2** [comment]
```
Vue.prototype.$firebaseAuth.eventBus.$on('onAuthStateChanged', (isLoggedIn) => {
        })
        ```
로그인 상태 변화 `event bus` 입니다

**Comment by jini031104** [comment]
로그인/로그인x 시 좋아요 버튼 활성화/비활성화 완료.
단, 로그인 시에는 새로고침을 해야만 좋아요 버튼 활성화가 반영됨. 해당 부분 수정 필요.
