### ISSUE TITLE
모바일상에서 게시하기 버튼 동작하지 않음

### ISSUE THREAD

**Issue by knh4437** [foodsns/Frontend#121]
https://user-images.githubusercontent.com/80094320/141064144-6bed21cf-2ac1-4dd5-8c60-ff72a4f11a50.mp4

같은 방식으로 컴퓨터에서 게시하기를 동작하면 정상적으로 글이 올라가지만, 모바일에서는 게시하기버튼이 눌리지 않음.

**Comment by stories2** [comment]
로그인을 안해서 그렇습니다

**Comment by knh4437** [comment]
앗...죄송합니다 ㅎㅎ
