### ISSUE TITLE
글쓰기: 사진 편집창에서 90도로 회전해도 올라간 게시물에는 적용되지 않음

### ISSUE THREAD

**Issue by jini031104** [foodsns/Frontend#126]
### 과정

![rufrhk](https://user-images.githubusercontent.com/90189794/141750168-4c992154-13e8-4544-bf31-f96ca2473f3f.png)

### 결과

![rufrhk](https://user-images.githubusercontent.com/90189794/141750344-2e6489ec-0bb9-4c34-b397-f07474be376e.png)

다음과 같이 올라간 게시물에는 사진 회전이 적용되지 않음.

**Comment by knh4437** [comment]
(1) CropModal.vue로 전달되는 이미지를 담는 변수명은 this.file - `onFileChanged()`(유저가 사진 버튼을 클릭하여 사진을 업로드 하는 메소드) // `this.file = e.target.file[0]`
에서 `this.uploadOnePhoto(this.file)` 실행 // `this.cropModal.file = file`

(2) CropModal로부터 편집이후`(this.$emit('updatefileProp', this.croppedimg)`, WritePostUI에서 `updatefileProp()` 실행
// `this.post.img = file`

(3) 서버로 보내지는 파일 - `onSubmit()`에서 `this.uploadFileToServer(docID, this.file)`
// 이 때의 this.file은 편집된 이미지가 아닌 최초로 사용자가 올린 이미지인 `e.target.file[0]`가 서버에 올라가게 되는 거같음.

그럼 (2)에서 변경된 이미지 값인 file을 this.post.img로 받는 것이 아닌 파일에 올라가는 값 this.file = file로 하면
=> 'split' 오류뜸
Firebase에 올라가는 this.file은 FILE인데 this.file = file로 하면 "this.file = 이미지값" 이런 식으로 서로 안 맞아서 오류 뜨는 거 같음
<img width="657" alt="오류" src="https://user-images.githubusercontent.com/80094320/143849496-72246ff6-0054-4dcf-a3c5-1d15f9b1721c.png">
.

**Comment by stories2** [comment]
오류의 원인은 업로드한 파일의 이름이 없어서 나는 로직 오류입니다.

https://github.com/foodsns/Frontend/blob/ef05ef6da453e30a2283de416d5a875eae780d46/src/module/firebaseStorage.controller.js#L23

파일 업로드시 해당 파일의 메타 정보에서 `파일 이름` 을 가져와서 `.jpg` 같은 확장자 명을 참고하는데,

보통의 경우에는 각자 단말기의 파일 시스템에서 불러오기 때문에 파일 이름이 존재합니다.

하지만 이미지가 `cropper-js` 로 인해 수정이 되어버린 경우 새로 생성된 바이너리 이미지 파일이라서 기존에 가지고 있던 정보는 사라집니다.

https://github.com/foodsns/Frontend/blob/ef05ef6da453e30a2283de416d5a875eae780d46/src/components/WritePostUI.vue#L341-L342

이 상태로 `uploadfileProp` 메소드를 호출할 때 전달하는 값으로

`blob:http://localhost:8080/6b3cdc45-8dfb-4e0c-8783-75361028ee86`

따위의 blob 데이터가 저장된 url 을 가리키는 값으로만 전달이 되었고, 파일 이름이 없는 상태로 호출이 되어 오류가 발생했던 것입니다.

https://github.com/foodsns/Frontend/blob/ef05ef6da453e30a2283de416d5a875eae780d46/src/components/WritePostUI.vue#L343-L349

해결 방법으론 수정된 blob 파일을 읽어 들인 후,

임의로 `edited.png` 라는 이름을 강제로 설정한 뒤

`this.file` 변수에는 읽어들인 `blob` 객체를 적용하였습니다.

웹에서 blob 은 간단히 바이너리 파일을 가리킵니다. 이미지, 문서 파일 등등
