### ISSUE TITLE
사진 업로드 : 처음 이미지 업로드 후 두 번째 업로드를 했을 때 모달이 뜨지 않음

### ISSUE THREAD

**Issue by knh4437** [foodsns/Frontend#56]
https://user-images.githubusercontent.com/80094320/137711666-0d6c84c7-2342-4761-94d3-8149ae925278.mp4

**Comment by stories2** [comment]
2가지 문제점이 있었음

1. `input[type=file]` 의 값이 이전과 같은 값이 이미 써져있어 변화하는 이벤트 (`@change="uploadOnePhoto"`)가 호출되어지지 않는 부분
2. `crop-modal` 컴포넌트는 내부적으로 `mounted` 상태에 모달을 띄우라는 명령어를 호출하는데 `uploadOnePhoto` 메소드 내부에서 `this.cropModal.show` 값을 토글하면 제데로 동작하지 않음

`1.`
문제 해결 자체는 간단함
`input[type=file]`의 value 값을 초기화 시켜주면 됨
https://github.com/foodsns/Frontend/blob/e88107fb5ec9882a657a3a9e924726e6342d9341/src/components/MainBoard.vue#L251

`2.`
위의 `1.` 해결덕분에 파일 변화 감지 함수 `uploadOnePhoto` 메소드가 호출이 되어지지만 여전히 모달이 출력되어지지 않을 것

`crop-modal` 은 내부적으로 `mounted` 상태에서만 모달을 보이게 하고 있으므로 이 부분에서 여러 다른 해결 방법이 있겠지만 

단순하게 `uploadOnePhoto` 메소드 호출 직후 
`this.cropModal.show = false` 로 값 초기화 한 후

```
        if (file.size <= maxSize) {
            this.cropModal.show = true
            this.cropModal.file = file
            e.target.value = ''
        }
```

여기서 `this.cropModal.show = true` 값으로 토글하면 될 것이라 생각하지만 여전히 동작하지 않게 됨

이유는 `Vue.js` 는 각 데이터가 변화할때 DOM을 렌더링 하는데 위 경우엔 메소드 스코프에서 변화 순간이 너무 빨라 `Vue.js` 가 DOM 랜더링을 따라가지 못 하는 것

이를 위해 `nexttick` 이라는 함수가 있는데 한번 DOM 을 렌더링 한 다음 다음 렌더링 시점에 실행할 일련의 작업을 정의하면 됨

https://github.com/foodsns/Frontend/blob/e88107fb5ec9882a657a3a9e924726e6342d9341/src/components/MainBoard.vue#L247-L253

최종적으로 이런 형태가 될 것
