### ISSUE TITLE
게시물 목록 조회 과정에서 정렬 옵션이 필요함

### ISSUE THREAD

**Issue by stories2** [foodsns/Frontend#86]
좋아요 많은 순서데로, 최신 게시물 순서데로 같은 정렬 옵션 필요

**Comment by knh4437** [comment]
Dropdown을 이용하여 누적 좋아요순, 이번주 좋아요순, 최신순등 사용자가 기간을 선택하여 해당 기간동안의 좋아요순으로 게시물을 정렬하는 방식이 좋을 거같음. 기간을 사용자가 원하는대로 선택할 수 있어 시각적으로나 여러 가지 이점이 있을 거같음.

**Comment by stories2** [comment]
> 내가 쓴 게시물만 보기도 필요
> 
> #85 랑 연동하면 좋을 것 같음.
> 
> 좋아요 많은 순서대로같은 경우, 인기 게시물같은 경우에는 시간이 지나면 노출도가 많아지니 오히려 더 좋아요가 쌓일 것. 그렇게 되면 신규 좋아요가 많은 게시물은 오래된 좋아요 게시물에 묻힐 것이고, 신규 좋아요 게시물은 가장 먼저 노출이 불가하게 됨. 따라서 일주일 동안 받은 좋아요 개수를 보고, 그동안 누적된 좋아요 개수에 상관 없이 해당 기간 내에 좋아요를 가장 많이 받은 순으로 게시물을 노출하는 것이 좋아 보임.



> Dropdown을 이용하여 누적 좋아요순, 이번주 좋아요순, 최신순등 사용자가 기간을 선택하여 해당 기간동안의 좋아요순으로 게시물을 정렬하는 방식이 좋을 거같음. 기간을 사용자가 원하는대로 선택할 수 있어 시각적으로나 여러 가지 이점이 있을 거같음.

검색 기간을 지정하는 기능은 좋다고 생각하지만 사용된 DB 특성상 구현하기 힘들게 되었음

Firestore 의 경우 not equal 연산자는 쿼리 작성시 같은 필드 값에 대해서만 연산이 가능한 제약조건이 존재함, 

즉, 날짜에 대한 범위 연산을 하면 나머지 공개, 비공개 필터링 쿼리를 함께 쓰지 못하는 문제점이 발생함 

레퍼런스는 [링크](https://firebase.google.com/docs/firestore/query-data/queries#compound_queries)

아쉽지만 날짜 혹은 좋아요를 선택하여 오름/ 내림 차순 정렬하는 옵션을 제공하는 쪽으로 구현을 해야 함
